version: "3"

volumes:
  pihole_config:
  dnsmasq_config:
  dnscrypt_config:
#  traefik_toml: traefik/traefik.toml
#  acme_json: traefik/acme.json
networks:
  traefik-backend:
    external:
      name: traefik-backend
services:
  traefik:
    container_name: traefik
    image: traefik:1.7.2-alpine
    command:
      - --debug
    volumes:
      - "$PWD/traefik/traefik.toml:/traefik.toml"
      - "$PWD/traefik/acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    labels:
      - traefik.backend=traefik
      - traefik.port=7070
      - traefik.frontend.rule=Host:192.168.0.149
    networks:
      - traefik-backend
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
#      - "9090:80/tcp"
#      - "443:443/tcp"
    environment:
      ServerIP: 192.168.0.149
      TZ: 'Asia/Kolkata'
      WEBPASSWORD: 'Tony@Stark1'
      #WEB_PORT: 9090
      DNS1: 127.0.0.1#5053
      DNS2: 127.0.0.1#5053
    # Volumes store your data between container upgrades
    volumes:
      - 'pihole_config:/etc/pihole/'
      - 'dnsmasq_config:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    labels:
#      - traefik.http.middlewares.pihole.stripprefix.prefixes=/pihole
#      - traefik.http.middlewares.pihole.stripprefix.forceslash=false
#      - traefik.http.middlewares.pihole.replacepathregex.regex=^/(.*)
#      - traefik.http.middlewares.pihole.replacepathregex.replacement=/admin/$$1
#      - traefik.http.middlewares.pihole.addprefix.prefix=/admin
      - traefik.backend=pihole
      - traefik.frontend.rule=Host:192.168.0.149;PathPrefix:/pihole/;ReplacePathRegex:^/pihole/(.*) /admin/$$1
      - traefik.port=80
    networks:
      - traefik-backend
    restart: unless-stopped
  dnscrypt-proxy:
    container_name: dnscrypt-proxy
    image: phani8996/dnscrypt-proxy-rpi:latest
    volumes:
      - 'dnscrypt_config:/config'
    ports:
      - '5053:5053/udp'
    labels:
      - traefik.enable=false
    networks:
      - traefik-backend
    restart: unless-stopped
  jupyter:
    container_name: jupyter
    image: phani8996/jupyter-rpi:latest
#    ports:
#      - "8888:8888/tcp"
    labels:
      - traefik.backend=jupyter
#      - traefik.frontend.rule=Host:jupyter.rpi.lan
#      - traefik.http.middlewares.jupyter.replacepathregex.regex=^/(.*)
#      - traefik.http.middlewares.jupyter.replacepathregex.replacement=/jupyter/$$1
      - traefik.frontend.rule=Host:192.168.0.149;PathPrefix:/jupyter/
      - traefik.port=8888
    networks:
      - traefik-backend
    restart: unless-stopped
